name: xswap-analysis
channels:
  - conda-forge
dependencies:
  - conda-forge::ipykernel=5.1.0
  - conda-forge::ipywidgets=7.4.2
  - conda-forge::matplotlib=3.0.3
  - conda-forge::nb_conda_kernels=2.2.1
  - conda-forge::networkx=2.2
  - conda-forge::notebook=5.7.8
  - conda-forge::numpy=1.16.2
  - conda-forge::pandas=0.24.2
  - conda-forge::plotnine=0.5.1
  - conda-forge::python=3.7.3
  - conda-forge::requests=2.21.0
  - conda-forge::scikit-learn=0.20.3
  - conda-forge::scipy=1.2.1
  - conda-forge::seaborn=0.9.0
  - conda-forge::tqdm=4.31.1
  - conda-forge::xlrd=1.2.0
  - conda-forge::r-gridextra=2.3
  - conda-forge::r-tidyverse=1.2.1
  - conda-forge::r-hexbin=1.27.2
  - conda-forge::r-irkernel=0.8.15
  - conda-forge::r-ggextra=0.8
  - conda-forge::r-ggrepel=0.8.1
  - conda-forge::r-cowplot=0.9.4
  - conda-forge::r-plotroc=2.2.1
  - conda-forge::r-rocr=1.0_7
  - conda-forge::r-proc=1.15.0
  - pip:
    - git+https://github.com/hetio/hetmatpy@5ecb7cec827c54886e0ddd90c18fbb69ce9b8ce1
    - git+https://github.com/greenelab/xswap@59e6c0c13dcdf7f94ba798d4300cdf75903e96b0
    # - git+https://github.com/andreagobbi/pyBiRewire@d27e837d41abefd18352c1ee4dc7295e2487d5be
