name: xswap-analysis
channels:
  - conda-forge
dependencies:
  - conda-forge::cython=0.29.2
  - conda-forge::python-igraph
  - conda-forge::ipykernel=4.8.2
  - conda-forge::ipywidgets=7.4.0
  - conda-forge::r-ggplot2=3.1.0
  - conda-forge::r-plotroc=2.2.1
  - conda-forge::r-irkernel=0.8.14
  - conda-forge::r-tidyverse=1.2.1
  - conda-forge::matplotlib=3.0.2
  - conda-forge::nb_conda_kernels=2.1.1
  - conda-forge::networkx=2.2
  - conda-forge::notebook=5.6.0
  - conda-forge::numpy=1.15.1
  - conda-forge::pandas=0.23.4
  - conda-forge::plotnine=0.5.1
  - conda-forge::python=3.6.6
  - conda-forge::requests=2.19.1
  - conda-forge::scikit-learn=0.20.2
  - conda-forge::scipy=1.1.0
  - conda-forge::seaborn=0.9.0
  - conda-forge::tqdm=4.24.0
  - conda-forge::xlrd=1.2.0
  - pip:
    - git+https://github.com/hetio/hetmatpy@ca29be378c3815882c9d3bd470463f353f18bfee
    - git+https://github.com/greenelab/xswap@59e6c0c13dcdf7f94ba798d4300cdf75903e96b0
    # - git+https://github.com/andreagobbi/pyBiRewire@d27e837d41abefd18352c1ee4dc7295e2487d5be
